FROM 'jupyterhub/jupyterhub:{{jupyterhub.version}}'

RUN pip install oauthenticator dockerspawner

# For debug purposes only
RUN apt-get update && apt-get install -y vim

COPY volume-naming-strategy ./volume-naming-strategy
RUN cd volume-naming-strategy && pip install .
