
version: '3'
services:

  jupyterhub:
    image: local/jupyterhub:0.9
    build:
      context: '.'

    hostname: jupyterhub

    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/var/local/jupyterhub/data:/var/local/jupyterhub/data/"
    - "/etc/jupyterhub/users.json:/etc/jupyterhub/users.json"
    - "/etc/jupyterhub/server.crt:/etc/jupyterhub/server.crt:ro"
    - "/etc/jupyterhub/server.key:/etc/jupyterhub/server.key:ro"
    - "$PWD/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py"
  
    networks:
    - 'jupyterhub_network'
   
    ports:
    - '443:8443'

    environment:
      DOCKER_NETWORK_NAME: 'jupyterhub_network'

    deploy:
      replicas: 1
      # ensure that we execute on a Swarm manager
      placement:
        constraints: [ 'node.role == manager' ]

networks:
  jupyterhub_network: {external: true}
