---

 #
 # Basic setup
 #

 - hosts: all 
   
   tasks:
   
   - debug: var=play_hosts
   - debug: var=groups.all
   
   - apt: update_cache=yes
   
   - apt: pkg={{item}} state=latest
     with_items: [ 'vim', 'tree', 'jq', 'curl', 'screen', 'htop', 'bash-completion']
  
   - hostname: name={{hostname}}
     when: hostname is defined

   - name: Update /etc/hosts with local hostname
     lineinfile:
       dest: /etc/hosts
       regexp: '^127\.0\.1\.1'
       line: '127.0.1.1 {{ansible_hostname}} {{hostname}}'
       state: present
     when: hostname is defined 

   - name: Update /etc/hosts with hostnames of this swarm
     lineinfile:
       dest: /etc/hosts
       line: '{{hostvars[item].ipv4_address}} {{hostvars[item].hostname}} {{item}}'
       insertafter: '^127\.0\.1\.1 .*'
     with_items: '{{groups.all}}'

   - group: name=wheel state=present
   
   - name: Add rules for sudoers (wheel)
     copy:
       dest: /etc/sudoers.d/wheel
       content: '%wheel ALL=(ALL) NOPASSWD:ALL'

   - file: path=~/bin state=directory
   
   - copy: src=files/{{item.key}} dest=~/{{item.value}} mode=0644
     with_dict: { 'profile': '.profile', 'bashrc': '.bashrc' }
    
   - authorized_key:
       user: root
       state: present
       key: '{{lookup("file", "keys/id_rsa.pub")}}'
   

 - hosts: manager

   tasks:

   - apt_repository: repo=ppa:deadsnakes/ppa state=present
   - apt: update_cache=yes
   
   - apt: pkg={{item}} state=latest
     with_items: [ 'python3.6', 'python3.6-venv', 'virtualenv' ]
   
   - name: Add user `jupyter` 
     user: name=jupyter shell=/bin/bash groups=wheel
      
   - file: path=/home/jupyter/bin state=directory owner=jupyter group=admin mode=0775
     with_items: [ '/home/jupyter/bin', '/home/jupyter/opt' ] 

   - authorized_key:
       user: jupyter
       state: present
       key: '{{lookup("file", "keys/id_rsa.pub")}}'

