---

#
# Setup NFS server
#

 - hosts: nfs

   vars:
     data_partition: ~
     fstype: 'xfs'
     mountpoint: {path: '/var/local/nfs', owner: 'nobody', group: 'nogroup', opts: 'defaults,pquota,uquota'} 
   
   roles:
   - 'local-fs'

   tasks:

   - stat: path=/var/local/nfs
     register: data_stat_result
   - assert:
       that: data_stat_result.stat.isdir

   - apt: pkg={{item}} state=latest
     with_items: [ 'nfs-kernel-server' ]

   - file: path={{item}} state=directory mode=0775 owner=nobody group=nogroup
     with_items: [ '/var/local/nfs/backups', '/var/local/nfs/jupyterhub' ]

   - name: Generate /etc/exports
     template:
       src: templates/nfs/exports.j2
       dest: /etc/exports

   - name: Reload /etc/exports
     shell: exportfs -a -v


#
# Setup NFS clients
#

 - hosts: all

   tasks:
    
   - set_fact:
       nfs_server: '{{hostvars["nfs"].hostname}}'

   - apt: pkg={{item}} state=latest
     with_items: [ 'nfs-common' ]

   - file: path={{item}} state=directory
     with_items: [ '/mnt/nfs-backups', '/mnt/nfs-jupyterhub' ]
    
   - name: Add entry in /etc/fstab for NFS directory
     mount: 
       name: /mnt/nfs-jupyterhub
       src: '{{nfs_server}}:/var/local/nfs/jupyterhub'
       fstype: nfs 
       opts: noauto,noexec,rsize=4096,hard,wsize=4096,intr
       state: present

