---
  
 #
 # Setup data directories for docker
 #

 - hosts: ['manager', 'workers']

   vars:
     #data_partition: /dev/sdc1
     data_partition: ~
     fstype: 'xfs'
     mountpoint: {path: '/var/lib/docker', owner: 'root', group: 'adm', opts: 'defaults,pquota'} 
   
   roles:
   - 'local-fs'

   tasks:
    
   - stat: path=/var/lib/docker
     register: data_stat_result
   - assert: 
       that: data_stat_result.stat.isdir


 #
 # Install docker service
 #

 - hosts: ['manager', 'workers']

   pre_tasks:

   - name: Check that a proper ipv4 network is specified
     assert:
       that: 
       - (network is defined) and (network | ipaddr("network"))
       - (ipv4_address is defined) and (ipv4_address | ipaddr(network))
      
   - set_fact:
       primary_ipv4_address: "{{ansible_all_ipv4_addresses| ipaddr(network)| first}}"
  
   - set_fact:    
       listen_address: '{{primary_ipv4_address}}'
     when: listen_to_primary_ipv4_address is defined

   - name: Check that primary ipv4 address is discovered into facts
     assert:
       that: primary_ipv4_address == ipv4_address

   vars:
     docker_compose_version: '1.16.1'

   roles:
   - 'docker-engine'

   tasks:

   - name: Create directories for trusted docker registries (if any)
     file: path=/etc/docker/certs.d/{{item.key}} state=directory mode=0755
     with_dict: '{{docker.registry}}'
   
   - name: Trust docker registries (if any)
     copy: src={{item.value.certificate}} dest=/etc/docker/certs.d/{{item.key}}/ca.crt
     with_dict: '{{docker.registry}}'
   
   - name: Restart docker service
     systemd: name=docker.service state=restarted

 - hosts: manager

   tasks: 

   - name: Add user `jupyter` to docker group
     user: name=jupyter groups=docker append=yes

