# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

inventory_file = ENV['INVENTORY_FILE'] || 'hosts.yml'

inventory = YAML.load_file(inventory_file)
inventory_vars = inventory['all']['vars']
inventory_groups = inventory['all']['children']
  
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

  config.vm.synced_folder "./vagrant-data/", "/vagrant", type: "rsync"

  # Define and provision manager

  config.vm.define "manager" do |manager|
    h = inventory_groups['manager']['hosts']['manager']
    manager.vm.network "private_network", ip: h['ipv4_address']
    manager.vm.provider "virtualbox" do |vb|
      vb.name = h['fqdn']
      vb.memory = 764
      vb.customize [ 'storageattach', :id, 
        '--storagectl', 'SCSI Controller',
        '--port', 2,
        '--device', 0,
        '--type', 'hdd',
        '--medium', File.absolute_path("data/manager/1.vdi")]
    end

    manager.vm.provision "setup-docker-swarm",  type: "ansible" do |ansible|
      ansible.playbook = 'play-docker-swarm.yml'
      ansible.limit = 'all' # do not limit to manager (take workers into play)
      ansible.become = true
      ansible.become_user = 'root'
      ansible.inventory_path = inventory_file
      ansible.verbose = true
    end
    
    manager.vm.provision "setup-jupyterhub", type: "ansible" do |ansible|
      ansible.playbook = 'play-jupyterhub.yml'
      ansible.limit = 'all'
      ansible.become = true
      ansible.become_user = 'root'
      ansible.inventory_path = inventory_file
      ansible.verbose = true
    end

  end

  # Define and provision workers

  inventory_groups['workers']['hosts'].keys.each do |worker_name|
    config.vm.define worker_name do |worker|
      h = inventory_groups['workers']['hosts'][worker_name]
      worker.vm.network "private_network", ip: h['ipv4_address']
      worker.vm.provider "virtualbox" do |vb|
         vb.name = h['fqdn']
         vb.memory = 512
         vb.customize [ 'storageattach', :id, 
           '--storagectl', 'SCSI Controller',
           '--port', 2,
           '--device', 0,
           '--type', 'hdd',
           '--medium', File.absolute_path("data/#{worker_name}/1.vdi")]
      end
    end
  end

  # Define and provision NFS server
  
  config.vm.define "nfs" do |nfs|
    h = inventory_groups['nfs']['hosts']['nfs']
    nfs.vm.network "private_network", ip: h['ipv4_address']
    nfs.vm.provider "virtualbox" do |vb|
      vb.name = h['fqdn']
      vb.memory = 384
      vb.customize [ 'storageattach', :id, 
        '--storagectl', 'SCSI Controller',
        '--port', 2,
        '--device', 0,
        '--type', 'hdd',
        '--medium', File.absolute_path("data/nfs/1.vdi")]
    end
  end  

  # Provision (common)
  
  config.vm.provision "file", source: "keys/id_rsa", destination: ".ssh/id_rsa"
  config.vm.provision "shell", path: "scripts/copy-key.sh", privileged: false

  config.vm.provision "file", source: "files/profile", destination: ".profile"
  config.vm.provision "file", source: "files/bashrc", destination: ".bashrc"

  config.vm.provision "shell", inline: <<-EOD
    apt-get update && apt-get install -y sudo python
  EOD
  
  config.vm.provision "setup-basic", type: "ansible" do |ansible| 
    ansible.playbook = 'play-basic.yml'
    ansible.become = true
    ansible.become_user = 'root'
    ansible.inventory_path = inventory_file
    ansible.verbose = true
  end
  
  config.vm.provision "setup-docker", type: "ansible" do |ansible| 
    ansible.playbook = 'play-docker.yml'
    ansible.become = true
    ansible.become_user = 'root'
    ansible.inventory_path = inventory_file
    ansible.verbose = true
  end

  config.vm.provision "setup-nfs", type: "ansible" do |ansible| 
    ansible.playbook = 'play-nfs.yml'
    ansible.become = true
    ansible.become_user = 'root'
    ansible.inventory_path = inventory_file
    ansible.verbose = true
  end

end
